// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cinemaAzureWebApp.Models;

namespace cinemaAzureWebApp.Migrations
{
    [DbContext(typeof(CinemaContext))]
    partial class CinemaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("cinemaAzureWebApp.Models.Cinema", b =>
                {
                    b.Property<short>("CinemaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    b.Property<short>("AmenitiesId")
                        .HasColumnType("smallint");

                    b.Property<string>("CinemaAddress")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CinemaName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<short>("CinemaScreens")
                        .HasColumnType("smallint");

                    b.HasKey("CinemaId");

                    b.ToTable("Cinema");
                });
#pragma warning restore 612, 618
        }
    }
}
